name: Build, Push, Deploy
on:
  push:
    branches: [ main ]
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: aws-actions/configure-aws-credentials@v2
        with: {...}
      - name: Build Docker Image
        run: |
          docker build -t ${{ env.ECR_URI }}:latest .
      - name: Push to ECR
        run: |
          aws ecr get-login-password | docker login --username AWS --password-stdin ${{ env.ECR_URI }}
          docker push ${{ env.ECR_URI }}:latest
      - name: Terraform Init & Apply
        working-directory: infra/terraform/environments/prod
        run: |
          terraform init
          terraform apply -auto-approve